### PR TITLE
Modify user_id field to be player in PlayerRating

### LINKED ISSUE #57: Modify PlayerRating field from user_id to player
in PlayerRating i want to modify the user_id field that is foreign key to the Player Table to be just player.

### PR DESCRIPTION
**Pull request by Danielsio**
### Desired Outcome

PlayerRating Class should have "player" field instead of "user_id"

### Implemented Changes
1. changed the user_id field to be "player" 
2. created the migration file again
all tests regarding creation of a PlayerRating have been changed
### Connected Issue/Story

Resolves #57

### CODE REVIEW

**Comment by Danielsio** [comment]
Feel free to go through the code, the changes are small, it's scope is only affecting the PlayerRating class

**Review by MaayanMashhadi — APPROVED** [review]

**Comment by yftacherzog** [comment]
See my comment [here](https://github.com/redhat-beyond/MeetBalls/pull/55#issuecomment-1528987601) regarding modifying migration files.

**Comment by Danielsio** [comment]
> See my comment [here](https://github.com/redhat-beyond/MeetBalls/pull/55#issuecomment-1528987601) regarding modifying migration files.

yes, well i have absolutley no idea if the outcome of the 0002 migrations stuff is the correct outcome i should have achived.

**Review by yftacherzog — APPROVED** [review]

**Comment by yftacherzog** [comment]
> > See my comment [here](https://github.com/redhat-beyond/MeetBalls/pull/55#issuecomment-1528987601) regarding modifying migration files.
> 
> yes, well i have absolutely no idea if the outcome of the 0002 migrations stuff is the correct outcome i should have achived.

I think it makes sense. It removed some constraints from the fields you changed so it can modify it, did the modifications and then applied the constraints on the renamed fields.

**Review by Yuval-Vino — APPROVED** [review]
LGTM 
Update your branch so it can be merged

**Comment by amitCohen2** [comment]
I see you made all the necessary changes, 
good job:)

**Pull request merged**
