### PR TITLE
Add notification icon button to navbar 

### LINKED ISSUE #113: Add a Notification Bell Icon to Navbar
**Expected Behavior**

Add new icon for notification with number of notifications

**Current Behavior**

There is no button for notifications in the current navbar

### PR DESCRIPTION
**Pull request by amitCohen2**
### Desired Outcome

Add notification bell button with number of notifications to the navbar.
It is only displayed when a user is logged in.

### Implemented Changes

- Modify base.html - add clickable notification bell button
- Modify styles.css - add css for this bell notification icon

### Connected Issue/Story

Resolves #113 

### Dependencies

This section inidicates whether this PR depends on any other PR's. 
Might need to wait for other PR's to merged before. Add the PR ID.
- [x] This PR depends on PR #111 
  changes

#### Test coverage

- [x] The changes in this PR do not require tests

#### Documentation

- [x] This PR does not require updating any documentation

### CODE REVIEW

**Comment by amitCohen2** [comment]
chrome_Im40YfgJXa

https://github.com/redhat-beyond/MeetBalls/assets/67042432/9d2b47df-aba8-4270-a74b-79588a6748a9

Please take a look and tell me what do you think about it

**Comment by Danielsio** [comment]
I think it's looks great !! Well Done !!

**Comment by ZvikaNaorCohen** [comment]
I've added these changes to my PR. Can you close this one?

**Comment by amitCohen2** [comment]
This added already in #111 PR.
Closed.

**Pull request closed without merging**
