### PR TITLE
Update ERD file

### LINKED ISSUE #89: Update ERD Diagrame
**Expected Behavior**
A ERD will include Notification entity

**Current Behavior**
Notification Entity does not exist.

### PR DESCRIPTION
**Pull request by amitCohen2**
### Desired Outcome

Update ERD file by adding a Notification entity.

### Implemented Changes

Modify 'ERD MetBalls.png' - add Notification entity 

### Connected Issue/Story

Resolves #89 

### Dependencies

- [x] This PR depends on PR #90 
  changes

#### Test coverage

- [x] The changes in this PR do not require tests

#### Documentation

- [x] ERD diagram were updated in this PR

### CODE REVIEW

**Comment by MaayanMashhadi** [comment]
Good idea to do that.
I know it isn't related to this PR, but I think it's small change for opening new PR,
but can you change in Game Event Player, the field name 'field' to be Player id? I think there is a mistake here.

**Comment by amitCohen2** [comment]
> Good idea to do that. I know it isn't related to this PR, but I think it's small change for opening new PR for it, but can you change in Game Event Player, the field name 'field' to be Player id? I think there is a mistake here.

Fixed

**Review by yftacherzog — APPROVED** [review]

**Review by Yuval-Vino — CHANGES_REQUESTED** [review]
how can `userID `be PK in notifications?  Can't a user have multiple notifications?

**Comment by amitCohen2** [comment]
> Collaborator

Added an 'ID' for PK , and the 'User ID' now is FK.

**Review by Yuval-Vino — APPROVED** [review]

**Pull request merged**
