### PR TITLE
Adding DFD file (Issue #14)

### PR DESCRIPTION
**Pull request by ZvikaNaorCohen**
Added DFD file and a folder of "documents" that would hold all the relevant documents for our project.

### CODE REVIEW

**Comment by ZvikaNaorCohen** [comment]
Issue link:
https://github.com/redhat-beyond/MeetBalls/issues/14

**Comment by Danielsio** [comment]
I took a look, and it looks great and detailed.
Good job, well done.

**Comment by MaayanMashhadi** [comment]
It looks great for me.
Good job!

**Review by yftacherzog — APPROVED** [review]
I'm going to have this merged. I don't have any significant comments. We can revisit it in the future if we notice issues during implementations.

**Comment by yftacherzog** [comment]
@ZvikaNaorCohen the issue would have been closed automatically if you mentioned it in the first comment (the PR description) along with one of the keywords mentioned here: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Pull request merged**
